version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: ${DB_PASSWORD:-app}
      POSTGRES_DB: shortener
    ports:
      - "5433:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    image: node:20
    working_dir: /app
    volumes:
      - ./server:/app
    command: sh -c "npm install && npm run dev"
    environment:
      DATABASE_URL: postgres://app:${DB_PASSWORD:-app}@postgres:5432/shortener
      BASE_URL: http://localhost:3001
      PORT: 3001
      REDIS_URL: redis://redis:6379
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis

  client:
    image: node:20
    working_dir: /app
    volumes:
      - ./client:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:8080"
    depends_on:
      - api
