CREATE TABLE IF NOT EXISTS links (
  id BIGSERIAL PRIMARY KEY,
  code VARCHAR(16) UNIQUE NOT NULL,
  long_url TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  clicks BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_links_code ON links(code);
